version: 2

sources:
  - name: raw
    database: MOVIELENS
    schema: RAW
    tables:
      - name: raw_genome_scores
      - name: raw_genome_tags
      - name: raw_movies
      - name: raw_ratings
      - name: raw_tags
      - name: raw_links